from pathlib import Path
from html import escape
out=Path(__file__).parent/'dist'
nav=[('','Início'),('sobre','Sobre'),('beneficios','Benefícios'),('empresas','Empresas'),('duvidas','Dúvidas')]
def btn(text,href,cls=''):
 return f'<a class="button {cls}" href="{href}">{text}<span class="arrow" aria-hidden="true">↗</span></a>'
def page(route,title,body):
 links=''.join(f'<a href="/{r+"/" if r else ""}" '+('aria-current="page"' if route==r else '')+f'>{t}</a>' for r,t in nav)
 html=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | Plano Mais</title><meta name="description" content="Mais cuidado para você e sua família. Conheça os planos e benefícios do Mais Assistencial."><meta name="theme-color" content="#213cb1"><link rel="icon" href="/assets/favicon.png"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><header><div class="wrap nav"><a href="/" aria-label="Mais Assistencial — início"><img class="logo" src="/assets/logo.svg" alt="Mais Assistencial"></a><nav class="links" id="navigation" aria-label="Navegação principal">{links}</nav>{btn('Conhecer os planos','/#planos')}<button class="menu" aria-expanded="false" aria-controls="navigation">Menu</button></div></header><main id="conteudo">{body}</main><footer><div class="wrap"><div class="footer-grid"><div><img class="logo" src="/assets/logo-white.svg" alt="Mais Assistencial"><p>Um plano pra vida toda.<br>Cuidado que faz parte do seu dia.</p></div><div><strong>Explore a Mais</strong>{links}</div><div><strong>Vamos conversar?</strong><a href="tel:08000955651">0800 095 5651</a><p>Segunda a sexta, das 8h às 20h.</p><a href="https://sales.planomais.com.br/">Atendimento e contratação ↗</a></div></div><div class="footer-bottom"><span>© 2026 Mais Assistencial. Todos os direitos reservados.</span><span>Plano assistencial familiar.</span></div></div></footer></body></html>'''
 html=html.replace('<link rel="stylesheet" href="/style.css">','<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/motion.css">')
 dest=out/route if route else out;dest.mkdir(parents=True,exist_ok=True);(dest/'index.html').write_text(html)
hero='''<div class="wrap hero"><div class="hero-grid"><div><div class="eyebrow">MAIS ASSISTENCIAL • PLANO PRA VIDA TODA</div><h1>A vida tem planos.<br>A gente tem<br><em>mais cuidado.</em></h1><p>Do cuidado com a saúde à proteção da família. Conte com benefícios que fazem a diferença todos os dias.</p>'''+btn('Encontre o seu plano','/#planos','light')+'''<p class="hero-note">Para você, sua família e cada fase da vida.</p></div><div class="hero-art" aria-label="Cartões dos planos Mais Assistencial"><div class="halo" aria-hidden="true"></div><img class="back" src="/assets/prime-3d.png" alt="Cartão Assistencial Prime"><img class="front" src="/assets/plus-3d.png" alt="Cartão Assistencial Plus"><div class="sticker">Mais tranquilidade ✦</div><div class="sticker bottom">Cabe na vida. Cuida de você.</div></div></div></div><div class="wrap ribbon"><span>Saúde e bem-estar</span><span>Benefícios no dia a dia</span><span>Cuidado com a família</span><span>Assistência de verdade</span></div>'''
hero='''<div class="wrap hero human-hero"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow">PLANO PRA VIDA TODA</div><h1>A vida fica melhor<br>com <em>mais cuidado.</em></h1><p>Para os grandes abraços. Para as pequenas conquistas. Para cuidar de você e de quem faz parte da sua vida.</p>'''+btn('Encontre o seu plano','/#planos','light')+'''<a class="hero-campaign-link" href="#campanhas">Conheça a campanha de fim de ano <span aria-hidden="true">↓</span></a></div><div class="human-visual"><div class="photo-mask"><img class="family-photo" src="/assets/familia.webp" width="1536" height="1024" alt="Pais e filha compartilhando um momento de carinho em casa" fetchpriority="high"></div><div class="photo-caption"><span class="caption-icon" aria-hidden="true">♡</span><span>O que importa merece<br><strong>mais cuidado.</strong></span></div><span class="photo-tag">Saúde, proteção e bem-estar</span></div></div></div><div class="wrap ribbon"><span>Saúde e bem-estar</span><span>Benefícios no dia a dia</span><span>Cuidado com a família</span><span>Assistência de verdade</span></div>'''
benefits=[('♡','Saúde mais perto','Consultas, exames e atendimento odontológico com valores reduzidos.','saude'),('✦','Seu dia rende mais','Uma rede de vantagens para incluir economia nos seus planos.','vantagens'),('⌂','Proteção para a família','Assistência funeral para amparar quem você ama nos momentos difíceis.','familia'),('♧','Seu pet também importa','O Petmais faz parte dos planos Prime e Platinum.','pet'),('+','Cuidado a distância','O Platinum inclui telemedicina para facilitar o acesso ao cuidado.','telemedicina'),('◇','Apoio quando precisar','Assistência jurídica entre os benefícios do Platinum.','apoio')]
def tiles(items):
 return '<div class="benefits">'+''.join(f'<article class="tile" id="{id}"><span class="icon" aria-hidden="true">{icon}</span><h3>{title}</h3><p>{text}</p><a class="text-link" href="/beneficios/#{id}">Conheça o benefício ↗</a></article>' for icon,title,text,id in items)+'</div>'
faqs=[('O que é o Plano Mais?','É um plano assistencial familiar que reúne benefícios para o dia a dia e assistência funeral. Os serviços disponíveis variam conforme o plano escolhido.'),('Qual é a diferença entre os planos?','O Plus reúne os benefícios essenciais. O Prime acrescenta o Petmais. O Platinum amplia o cuidado com especialidades médicas inclusas, telemedicina e assistência jurídica. Compare as opções e confirme as condições com a equipe.'),('Como faço para contratar?','Escolha a opção que combina com você e acesse o atendimento de contratação. A equipe orienta sobre adesão, pagamento e condições do plano.'),('Como consultar a rede de atendimento?','Entre em contato com a equipe para verificar os prestadores e a disponibilidade na sua região antes de agendar.'),('Posso incluir minha família?','Converse com a equipe sobre a inclusão de familiares. Quantidade de beneficiários, regras e valores devem ser confirmados na contratação.'),('Os benefícios estão disponíveis em qualquer cidade?','A disponibilidade pode variar conforme a região, o prestador e o plano. Consulte a equipe para conferir o atendimento na sua cidade.'),('Como verificar carências e regras de utilização?','Peça à equipe as condições do plano e leia o contrato antes de aderir. Ele deve esclarecer os prazos, limites e regras de cada serviço.')]
def faq(items): return ''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)
def cta():return '<div class="wrap cta"><h2>O próximo plano?<br>Cuidar de quem você ama.</h2>'+btn('Conhecer os planos','/#planos','light')+'</div>'
plans=[('Plus','24,90','plus',['Consultas e exames com descontos','Benefícios odontológicos','Clube de vantagens','Assistência funeral Plus']),('Prime','39,90','prime',['Benefícios do Plus','Assistência funeral Prime','Petmais']),('Platinum','89,90','platinum',['Cardiologia, clínica geral, ginecologia e pediatria inclusas e ilimitadas','Benefícios odontológicos e clube de vantagens','Assistência funeral e Petmais','Telemedicina e assistência jurídica'])]
planhtml='<section class="section plans-section" id="planos"><div class="wrap"><div class="heading"><div><div class="eyebrow">UM PLANO QUE COMBINA COM VOCÊ</div><h2>Mais possibilidades.<br>O seu jeito de cuidar.</h2></div><p class="muted">Compare os benefícios e encontre o cuidado que faz sentido para a sua família.</p></div><div class="plans">'
for name,price,img,features in plans:
 planhtml+=f'<article class="plan {"featured" if name=="Prime" else ""}"><div class="plan-visual"><img loading="lazy" src="/assets/{img}.png" alt="Cartão Assistencial {name}"></div><div class="eyebrow no-margin">ASSISTENCIAL</div><h3>{name}</h3><div class="price"><small>R$</small> {price}<small> /mês</small></div><ul>'+''.join(f'<li>{v}</li>' for v in features)+'</ul>'+btn('Conhecer o '+name,'https://sales.planomais.com.br/','' if name=='Prime' else 'outline')+'</article>'
planhtml+='</div><p class="footnote">Valores anunciados na página de vendas, consultados em 19/09/2026. Benefícios, disponibilidade, abrangência e condições de adesão devem ser confirmados na contratação. <a class="text-link" href="https://sales.planomais.com.br/">Consultar condições</a>.</p></div></section>'
company='<section class="section"><div class="wrap company"><div><div class="eyebrow">MAIS CONEXÕES, MAIS CUIDADO</div><h2>Empresas e pessoas.<br>Mais perto.</h2><p>Quer conversar sobre benefícios para sua equipe ou fazer parte da rede de parceiros? Vamos encontrar o caminho com você.</p>'+btn('Mais para empresas','/empresas/')+'</div><aside><div>01 &nbsp; Benefícios para sua equipe</div><div>02 &nbsp; Conexões com a rede Mais</div><div>03 &nbsp; Atendimento para sua empresa</div></aside></div></section>'
# Campanhas demonstrativas são identificadas; depoimentos exigem conteúdo aprovado.
import json
editorial=json.loads((Path(__file__).parent/'content.json').read_text())
extras=''
for c in editorial['campaigns']:
 extras+=f'<section class="section wrap campaign-section" id="campanhas" aria-labelledby="campaign-heading"><div class="heading"><div><div class="eyebrow">CAMPANHAS MAIS</div><h2 id="campaign-heading">Mais motivos para<br>estar perto.</h2></div><span class="campaign-season">FIM DE ANO · 2026</span></div><article class="campaign"><div class="campaign-copy"><span class="demo-badge">Campanha demonstrativa</span><h3>{escape(c["title"])}</h3><p>{escape(c["description"])}</p>{btn(escape(c["label"]),escape(c["url"]),"light")}<p class="campaign-note">Simulação criativa de fim de ano. Não representa uma oferta comercial vigente.</p></div><div class="campaign-photo"><img loading="lazy" src="{escape(c["image"])}" width="1536" height="1024" alt="{escape(c["image_alt"])}"><span class="campaign-photo-label">Mais encontros.<br>Mais histórias juntos.</span></div></article></section>'
if editorial['testimonials']:
 extras+='<section class="section wrap"><h2>Quem vive com Mais conta.</h2><div class="benefits">'+''.join(f'<blockquote class="tile"><p>{escape(t["quote"])}</p><cite>{escape(t["name"])}</cite></blockquote>' for t in editorial['testimonials'])+'</div></section>'
cardstory='''<section class="card-story" aria-labelledby="card-story-title"><div class="card-story-sticky"><div class="wrap card-story-grid"><div class="card-story-copy"><div class="eyebrow">COM VOCÊ, EM CADA FASE</div><h2 id="card-story-title">Pequeno no tamanho.<br><em>Grande no cuidado.</em></h2><p>Um cartão. Muitas formas de estar perto. Conheça os planos que acompanham a sua família no dia a dia.</p>'''+btn('Compare os planos','/#planos')+'''<div class="story-progress" aria-hidden="true"><span></span></div><p class="scroll-hint">Continue rolando para conhecer as opções ↓</p></div><div class="card-stage" aria-label="Cartões Plus, Prime e Platinum"><div class="stage-orbit" aria-hidden="true"></div><figure class="motion-card motion-plus"><img src="/assets/plus.png" width="697" height="1075" loading="lazy" alt="Cartão do plano Plus"><figcaption>Plus</figcaption></figure><figure class="motion-card motion-prime"><img src="/assets/prime.png" width="697" height="1075" loading="lazy" alt="Cartão do plano Prime"><figcaption>Prime</figcaption></figure><figure class="motion-card motion-platinum"><img src="/assets/platinum.png" width="697" height="1075" loading="lazy" alt="Cartão do plano Platinum"><figcaption>Platinum</figcaption></figure><span class="stage-label">Seu plano. Seu momento.</span></div></div></div></section>'''
home=hero+'<section class="section wrap"><div class="heading"><div><div class="eyebrow">PRESENTE NO SEU DIA A DIA</div><h2>Tem mais vida<br>nos seus benefícios.</h2></div><a class="text-link" href="/beneficios/">Explore todos os benefícios ↗</a></div>'+tiles(benefits[:3])+'</section>'+cardstory+extras+company+planhtml+'<section class="section wrap faq-grid"><div><div class="eyebrow">PODE PERGUNTAR</div><h2>Menos dúvidas.<br>Mais tranquilidade.</h2><p class="muted">A gente ajuda você a entender cada detalhe antes de escolher.</p><a class="text-link" href="/duvidas/">Veja todas as dúvidas ↗</a></div><div>'+faq(faqs[:4])+'</div></section>'+cta()
page('','Um plano pra vida toda',home)
def inner(tag,title,text):return f'<div class="wrap inner-hero"><div class="eyebrow">{tag}</div><h1>{title}</h1><p>{text}</p></div>'
page('sobre','Sobre a Mais',inner('SOMOS A MAIS','Cuidar faz parte<br>de quem a gente é.','A vida acontece em muitos momentos. Nosso propósito é estar perto das pessoas em cada um deles.')+'<section class="section wrap story"><div><div class="eyebrow">PLANO PRA VIDA TODA</div><h2>Para o cotidiano.<br>Para quem importa.</h2><p>A Mais Assistencial reúne cuidado e benefícios em um plano pensado para acompanhar as famílias. Da busca por atendimento à proteção nos momentos delicados, queremos tornar essa jornada mais simples.</p><p class="muted">Uma conversa próxima, informações claras e respeito por cada história. É assim que acreditamos que o cuidado começa.</p></div><div class="story-callout">A gente acredita que cuidar é estar presente.<br><br>Com atenção.<br>Com respeito.<br>Com mais humanidade.</div></section><section class="section wrap"><div class="steps"><article><div class="step-number">01</div><h3>Simples para entender</h3><p>Benefícios apresentados com clareza para ajudar você a escolher.</p></article><article><div class="step-number">02</div><h3>Próximo de você</h3><p>Uma comunicação humana, acolhedora e respeitosa.</p></article><article><div class="step-number">03</div><h3>Presente na vida</h3><p>Cuidado para o dia a dia e apoio nos momentos que pedem atenção.</p></article></div></section>'+cta())
page('beneficios','Benefícios',inner('CUIDADO QUE ACOMPANHA','Mais benefícios.<br>Mais motivos para viver bem.','Conheça as possibilidades de cuidado e confira quais fazem parte de cada plano.')+'<section class="section wrap">'+tiles(benefits)+'<p class="footnote">A utilização depende do plano, da rede disponível e das condições contratuais. Consulte a equipe para confirmar os detalhes.</p></section>'+planhtml+cta())
page('empresas','Para empresas',inner('MAIS PARA EMPRESAS','Boas conexões começam<br>com cuidado.','Um espaço para empresas que querem conversar sobre benefícios ou se aproximar da rede Mais.')+'<section class="section wrap"><div class="story"><article class="tile"><span class="icon" aria-hidden="true">♡</span><h2>Para a sua equipe</h2><p>Quer conhecer as possibilidades de benefícios para as pessoas que trabalham com você? Conte à equipe Mais o que sua empresa procura.</p>'+btn('Conversar sobre benefícios','tel:08000955651')+'</article><article class="tile"><span class="icon" aria-hidden="true">✦</span><h2>Para novos parceiros</h2><p>Sua empresa oferece serviços e tem interesse em uma parceria? Entre em contato para apresentar seu negócio e conhecer as possibilidades.</p>'+btn('Falar sobre uma parceria','tel:08000955651','outline')+'</article></div></section><section class="section wrap"><div class="heading"><div><div class="eyebrow">VAMOS CONVERSAR</div><h2>Conte com um<br>atendimento próximo.</h2></div><p>Informe sua cidade, o nome da empresa e o motivo do contato. Nossa conversa começa por aí.</p></div><div class="contact"><span>Central de atendimento</span><a href="tel:08000955651">0800 095 5651 ↗</a><small>Segunda a sexta, das 8h às 20h.</small></div></section>'+cta())
page('duvidas','Dúvidas frequentes',inner('RESPOSTAS COM CLAREZA','Toda boa escolha começa<br>com informação.','Tire suas dúvidas sobre os planos, os benefícios e os próximos passos.')+'<section class="section wrap"><div class="page-faq">'+faq(faqs)+'</div></section><section class="section wrap"><div class="company"><div><h2>A sua dúvida<br>não está aqui?</h2><p>A equipe Mais pode ajudar com as informações específicas do seu plano.</p></div><div class="contact"><span>Fale com a gente</span><a href="tel:08000955651">0800 095 5651 ↗</a><small>Segunda a sexta, das 8h às 20h.</small></div></div></section>')
